name: Continous Builds

on:
  push:
    branches: [qt6]

jobs:
  
  job_4:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install qt
        run: |
          pip install aqtinstall
          python3 -m aqt install-qt -O ${{ github.workspace }}/Qt/ mac desktop 6.2.1
          echo "${{ github.workspace }}/Qt/6.2.1/macos/bin/" >> $GITHUB_PATH
          export PATH=$PATH:"${{ github.workspace }}/Qt/6.2.1/clang_64/bin/"
          brew update
          brew upgrade
          brew install boost traildb/judy/judy
          brew install mariadb cmake
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
          ./build_qsql.sh 6.2.1 mac
          cd ${{ github.workspace }}/qtbase/src/plugins/sqldrivers/
          mkdir -p mariadb_driver/plugins/sqldrivers
          cp plugins/sqldrivers/libqsqlmysql.dylib mariadb_driver/plugins/sqldrivers
          cp /usr/local/lib/libmariadb.dylib mariadb_driver/
      - name: Mac artefact
        uses: actions/upload-artifact@v1
        with:
          name: MacOS
          path: ${{ github.workspace }}/qtbase/src/plugins/sqldrivers/mariadb_driver/
